# Generated by Django 5.1.4 on 2025-01-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire_Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='থানার নাম')),
                ('location', models.CharField(max_length=200, verbose_name='ঠিকানা')),
                ('image', models.ImageField(upload_to='Fire_Service/images/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='ফোন নম্বর')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='মোবাইল নম্বর')),
                ('tel_mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='টেল মোবাইল')),
            ],
        ),
    ]
