# Generated by Django 5.1.4 on 2025-01-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fire_station',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fire_station',
            name='tel_mobile',
        ),
        migrations.AddField(
            model_name='fire_station',
            name='telMobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fire_station',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fire_station',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fire_station',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fire_station',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
