# Generated by Django 5.1.4 on 2025-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_service', '0002_remove_fire_station_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire_station',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Fire_service/images'),
        ),
    ]
