# Generated by Django 5.1.4 on 2025-01-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_service', '0003_fire_station_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fire_Station',
            new_name='FireStation',
        ),
    ]
