# Generated by Django 5.1.4 on 2025-01-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='user/cover_photo'),
        ),
    ]
