# Generated by Django 5.1.4 on 2025-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='union',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
