# Generated by Django 5.1.4 on 2025-01-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_phohne_number_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
