# Generated by Django 5.1.4 on 2025-01-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='doctor.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('সোমবার', 'সোমবার'), ('মঙ্গলবার', 'মঙ্গলবার'), ('বুধবার', 'বুধবার'), ('বৃহস্পতিবার', 'বৃহস্পতিবার'), ('শুক্রবার', 'শুক্রবার'), ('শনিবার', 'শনিবার'), ('রবিবার', 'রবিবার')], max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctor.doctor')),
            ],
        ),
    ]
